### ISSUE TITLE
Files cannot be downloaded

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#24]
Currently no files from the CTFpad can be downloaded.

For instance, when trying to download the following file: `https://ctf.realraum.at:1234/file/b37fc879776df3e0d65bb542f718d4fd6501a6575c046b6a597408d934c93afb/handout-af78913b8dd5e7dfca5102ad99f4bfb262ceefd5.tgz`, one gets the error
```
Unable to connect
Firefox can’t establish a connection to the server at ctf.realraum.at:1234.
```

**Comment by stefan2904** [comment]
```
_http_outgoing.js:506
    throw new errors.TypeError('ERR_INVALID_CHAR', 'header content', name);
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Type"]
    at validateHeader (_http_outgoing.js:506:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.res.setHeader (/opt/ctfpad/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/opt/ctfpad/node_modules/express/lib/response.js:595:10)
    at /opt/ctfpad/main.coffee:357:13
    at /opt/ctfpad/database.coffee:192:60
    at Statement.<anonymous> (/opt/ctfpad/database.coffee:210:10)

```

**Comment by stefan2904** [comment]
I guess we should pull from upstream ...

https://github.com/StratumAuhuur/CTFPad/commit/8d4e0ceefd218fba8bda2b1f360a40da502867f5

**Comment by kaydoubleu** [comment]
thanks @stefan2904!
